# Site settings
title: Story
theme: jekyll-theme-cayman
description: -
cover: yokerest/image/radhakrishna.jpg
logo: yokerest/image/test.png
favicon: yokerest/image/favicon.png
url: "https://yokerest.github.io/hanmuman/" # the base hostname & protocol for your site e.g. "https://yokerest.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
